### ISSUE TITLE
libnotify gem と ffi gem の pkgsrc への追加

### ISSUE THREAD

**Issue by tsutsui** [tsutsui/netbsd-teokureliveimage#22]
#21#issuecomment-502443571 の通り mikutter 3.9.0 では libnotify gem が必要になるが
現状の pkgsrc には存在しない（依存で必要な ffi gem もない）ので追加が必要。

通知自体はダミーの libnotify を入れるという手もありそうだが、
まずは正攻法で動くのか試してみる。

**Comment by tsutsui** [comment]
見落としていたけれど、 pkgsrc/devel/ruby-ffi は存在してた。
http://pkgsrc.se/devel/ruby-ffi
とりあえず 1.10.0 → 1.11.1 の更新だけしておく?

**Comment by tsutsui** [comment]
適当に sysutils/ruby-libnotify を作って mikutter develop ff0fcbe を動かしてみたが、
以下のエラーで起動しない。
```
% ruby24 mikutter.rb
/usr/pkg/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach': unhandled exception
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach_function'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/ffi.rb:32:in `attach_functions!'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/ffi.rb:12:in `included'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/api.rb:9:in `include'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/api.rb:9:in `<class:API>'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/api.rb:8:in `<module:Libnotify>'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify/api.rb:4:in `<top (required)>'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/pkg/lib/ruby/gems/2.4.0/gems/libnotify-0.9.4/lib/libnotify.rb:2:in `<top (required)>'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/tsutsui/mikutter/mikutter/core/plugin/libnotify/libnotify.rb:4:in `<top (required)>'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:158:in `load'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:158:in `block in load'
        from /home/tsutsui/mikutter/mikutter/core/utils.rb:299:in `block in atomic'
        from /usr/pkg/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from /home/tsutsui/mikutter/mikutter/core/utils.rb:299:in `atomic'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:146:in `load'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:98:in `block in load_all'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:38:in `block in each_spec'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:33:in `each'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:33:in `each'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:36:in `each_spec'
        from /home/tsutsui/mikutter/mikutter/core/miquire_plugin.rb:96:in `load_all'
        from /home/tsutsui/mikutter/mikutter/core/boot/load_plugin.rb:10:in `<top (required)>'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/pkg/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:75:in `each'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:75:in `miquire'
        from /home/tsutsui/mikutter/mikutter/core/miquire.rb:18:in `miquire'
        from mikutter.rb:43:in `<main>
```

時間切れになりそう……

**Comment by tsutsui** [comment]
https://dev.mikutter.hachune.net/issues/1349
謎マシンに配慮(?)いただいて ffi + libnotify gem 利用の変更方針は取り下げられたので、
こちらもいったんクローズ。
