### ISSUE TITLE
mikutterが `GLib::Error` で起動しないことがある

### ISSUE THREAD

**Issue by tsutsui** [tsutsui/netbsd-teokureliveimage#57]
NetBSD 10.0_RC2 にする前からだと思うが、
mikutterを起動する時に以下のようなエラーが出て mikutter の起動に失敗することがある。

```
GLib::Error Could not locate gtk_events_pending: 'gtk_events_pending': /usr/pkg/
bin/ruby32: Shared object "nss_compat.so.0" not found
/usr/pkg/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.1/lib/gobject-intros
pection/loader.rb:711:in `invoke'
/usr/pkg/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.1/lib/gobject-intros
pection/loader.rb:711:in `invoke'
/usr/pkg/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.1/lib/gobject-intros
pection/loader.rb:118:in `events_pending?'
{MIKUTTER_DIR}/plugin/gtk3/mainloop.rb:15:in `block (2 levels) in mainloop'
{MIKUTTER_DIR}/plugin/gtk3/mainloop.rb:11:in `loop'
{MIKUTTER_DIR}/plugin/gtk3/mainloop.rb:11:in `block in mainloop'
{MIKUTTER_DIR}/plugin/gtk3/mainloop.rb:9:in `catch'
{MIKUTTER_DIR}/plugin/gtk3/mainloop.rb:9:in `mainloop'
{MIKUTTER_DIR}/mikutter.rb:77:in `boot!'
{MIKUTTER_DIR}/mikutter.rb:113:in `<main>'
```

メインマシンでは過去からそこそこ起きていたものの環境依存なのかが判断できていなかったが、
Ruby 3.2 にした 20240420版 Live Imageでもそれなりの頻度で起きることがあるようなので
こちらに書いておく。

**Comment by tsutsui** [comment]
glib2 というか gobject introspection の `dlsym()` + `dlerror()` 呼び出しの実装と
NetBSD の `dlerror()` が thread safe ではないという組み合わせの問題で、
pkgsrc/devel/gilb2 側を
https://mail-index.netbsd.org/pkgsrc-changes/2026/04/30/msg345277.html
で修正した。
